data <- read.csv("Country-data.csv")
View(data)
str(data)
library(factoextra)
library(tidyverse)
library(cluster)
library(dendextend)
library(animation)
data <- na.omit(data)
data<-read.csv('Country-data.csv')
View(data$country)
data1<-scale(data[,c(2:10)])
data<-cbind(data$country,data1)
View(data)
distance <- dist(data,method = 'euclidean')
view(distance)
#single linkage
hcluster <- hclust(distance,method = 'single')
plot(hcluster,cex = 0.8,hang = -1)
hcluster1 <- agnes(distance,method = 'single')
plot(hcluster1,,cex = 0.5,hang = -1)
#complete Linkage
hcluster2 <- hclust(distance,method = 'complete')
plot(hcluster2,cex = 0.8,hang = -1)
hcluster3 <- agnes(distance,method = 'complete')
plot(hcluster3,cex = 0.5,hang = -1)
#centroid
hcluster4 <- hclust(distance,method = 'centroid')
plot(hcluster4,cex = 0.8,hang = -1)
hcluster5 <- agnes(distance,method = 'centroid')
plot(hcluster5,cex = 0.5,hang = -1)
#ward
hcluster6 <- hclust(distance,method = 'ward.D')
plot(hcluster6,cex = 0.8,hang = -1)
hcluster7 <- agnes(distance,method = 'ward')
plot(hcluster7,cex = 0.5,hang = -1)
#average
hcluster8 <- hclust(distance,method = 'average')
plot(hcluster8,cex = 0.8,hang = -1)
hcluster9 <- agnes(distance,method = 'average')
plot(hcluster9,cex = 0.5,hang = -1)
#cophenetic corelation
hcluster_co <- cophenetic(hcluster) 
cor(distance,hcluster_co)
hcluster_co1 <- cophenetic(hcluster1) 
cor(distance,hcluster_co1)
hcluster_co2 <- cophenetic(hcluster2) 
cor(distance,hcluster_co2)
hcluster_co4 <- cophenetic(hcluster4) 
cor(distance,hcluster_co4)
hcluster_co6 <- cophenetic(hcluster6) 
cor(distance,hcluster_co6)
hcluster_co8 <- cophenetic(hcluster8) 
cor(distance,hcluster_co8)
plot(distance,hcluster_co8)
plot(distance,hcluster_co)
#if cophenetic correlation is high data is closely packed in a single line.
#if gower distance id lower clustering method is better
godists <- sum((distance-hcluster_co)^2)
godists1 <- sum((distance-hcluster_co8)^2)
data <- read.csv("Country-data.csv",sep = ",",dec = ".",header = TRUE,row.names = 1)
data <- na.omit(data)
data <- scale(data)
rect.hclust(hcluster8,k = 10,border = 2:10)

#parallel analysis
library(psych)
library(GPArotation)
NOF<-fa.parallel(data, fm = "minres", fa = 'fa')
Fact_Ana = fa(data,nfactors = 5,rotate = "oblimin", fm = "minres")
print(Fact_Ana$loadings,cutoff = 0.4)
#Kmeans clustering

kmeans(data,3)
kmeans.ani(data)
kmeans.ani(data,3)
KM <- kmeans(data,3,nstart=50)
KM$cluster
data1 <- cbind(data, cluster = KM$cluster)
KM1 <- eclust(data,"kmeans",nstart = 25)
fviz_gap_stat(KM1$gap_stat)
fviz_silhouette(KM1)
