library(factoextra)
library(cluster)
library(animation)
data('USArrests')
Data <- scale(USArrests)
str(Data)
kmeans(Data, 4)
kmeans.ani(Data, 4)
KM <- kmeans(Data, 4, nstart = 50)
Data1 <- cbind(Data, cluster = KM$cluster)
KM1 <- eclust(Data, "kmeans", nstart = 25)
fviz_gap_stat(KM1$gap_stat)
fviz_silhouette(KM1)