library(tidyverse)
library(cluster)
library(factoextra)
library(dendextend)
data <- USArrests
View(data)
data <- na.omit(data)
data <- scale(data)
View(data)
distance <- dist(data,method = 'euclidean')
view(distance)
#single linkage
hcluster <- hclust(distance,method = 'single')
plot(hcluster,cex = 0.8,hang = -1)
hcluster1 <- agnes(distance,method = 'single')
plot(hcluster1,cex = 0.5,hang = -1)
#complete Linkage
hcluster2 <- hclust(distance,method = 'complete')
plot(hcluster2,cex = 0.8,hang = -1)
hcluster3 <- agnes(distance,method = 'complete')
plot(hcluster3,cex = 0.5,hang = -1)
#centroid
hcluster4 <- hclust(distance,method = 'centroid')
plot(hcluster4,cex = 0.8,hang = -1)
hcluster5 <- agnes(distance,method = 'centroid')
plot(hcluster5,cex = 0.5,hang = -1)
#ward
hcluster6 <- hclust(distance,method = 'ward.D')
plot(hcluster6,cex = 0.8,hang = -1)
hcluster7 <- agnes(distance,method = 'ward')
plot(hcluster7,cex= 0.5,hang = -1)
#average
hcluster8 <- hclust(distance,method = 'average')
plot(hcluster8,cex = 0.8,hang = -1)
hcluster9 <- agnes(distance,method = 'average')
plot(hcluster9,cex =0.5,hang =-1)
#cophenetic corelation
hcluster_co <- cophenetic(hcluster) 
cor(distance,hcluster_co)
hcluster_co1 <- cophenetic(hcluster1) 
cor(distance,hcluster_co1)
hcluster_co2 <- cophenetic(hcluster2) 
cor(distance,hcluster_co2)
hcluster_co4 <- cophenetic(hcluster4) 
cor(distance,hcluster_co4)
hcluster_co6 <- cophenetic(hcluster6) 
cor(distance,hcluster_co6)
hcluster_co8 <- cophenetic(hcluster8) 
cor(distance,hcluster_co8)
plot(distance,hcluster_co8)
plot(distance,hcluster_co)
#if cophenetic correlation is high data is closely packed in a single line.
#if gower distance id lower clustering method is better
godists <- sum((distance-hcluster_co)^2)
godists1 <- sum((distance-hcluster_co8)^2)
